### ISSUE TITLE
Dungeons, query_z & pathing.

### ISSUE THREAD

**Issue by devw4r** [namreeb/namigator#39]
Both not working inside dungeons. Probably related to #38.

![image](https://user-images.githubusercontent.com/108442943/211454427-863a0071-820f-433c-9779-8c6542260f55.png)

**Comment by namreeb** [comment]
I tried pathing in the doorway in the screenshot and it worked.  That could be because of the query_z fixes, I'm not sure.  But I think this can be closed too?

**Comment by devw4r** [comment]
I will re check later today @namreeb , will post back here.

**Comment by devw4r** [comment]
Apparently, this has to do with still wrong Z (Above terrain) being returned when mobs are chasing you inside a cave and running alongside a wmo wall, for now I added some checks in order to prevent trusting namigator Z on this scenarios.
https://github.com/The-Alpha-Project/alpha-core/pull/917/files

**Comment by namreeb** [comment]
Okay thanks that is useful insight.  I'm trying to get the alpha core running locally right now.

**Comment by devw4r** [comment]
![image](https://user-images.githubusercontent.com/108442943/221465124-385f3ac8-6d0c-4e31-860e-67f43cba1293.png)
Namigator returned wrong Z: 122.01835632324219 for 2052.188232421875 1834.0185546875 107.90196228027344 Map 0

![image](https://user-images.githubusercontent.com/108442943/221465175-f15baf05-a70d-42e4-a680-33ad6e61cfc8.png)
Namigator returned wrong Z: 117.56498718261719 for 2050.06396484375 1843.5313720703125 106.02456665039062 Map 0

![image](https://user-images.githubusercontent.com/108442943/221465266-5eb9e97d-dd4b-449a-bd16-bbeefd69cd01.png)
Namigator returned wrong Z: 124.09246063232422 for 2038.1925048828125 1843.1253662109375 105.71818542480469 Map 0

**Comment by namreeb** [comment]
Leaving myself some notes here.

> Namigator returned wrong Z: 122.01835632324219 for 2052.188232421875 1834.0185546875 107.90196228027344 Map 0

![image](https://user-images.githubusercontent.com/5429489/232281703-74c00f5f-2b3a-48cd-845f-fc7294074081.png)

I think the problem here is that we are using the mesh for the hint to the Z search(es), but as you can see in the screenshot above, that inside corner is not part of the mesh.  This is because of having eroded the walkable edges.  I can see two possible solutions here:
* Do not rely on the mesh for the z hint to start the search
* Do not erode the walkable edges

I'm leaning towards the latter because, as evidenced by the screenshot you posted, it certainly is reachable.

**Comment by namreeb** [comment]
https://github.com/namreeb/namigator/commit/6ccbe817c6555e2683f60fb73cedba3dadde46b1 ended up fixing this, hopefully.  But I went with option A from the post above.  After experimenting with different mesh settings, I couldn't find a way to make the mesh go all the way into this corner and still be a net positive impact overall.  I added some code for the second z query scenario, which is from a start (x,y,z) to a finish (x', y') along the mesh.
